[v1]
"imessage-exporter 2.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["imessage-exporter"]
"rustlings 6.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustlings"]
